company = input()
company_adress = input()
phone_number = input()
fax_number = input()
web_site = input()
first_name = input()
second_name = input()
years = input()
manager_phone = input()

print(company)
print(f'Address: {company_adress}')
print(f'Tel. {phone_number}')
print(f'Fax: (no fax)')
print(f'Web site: {web_site}')
print(f'Manager: {first_name} {second_name} (age: {years}, tel. {manager_phone})')
